AWSTemplateFormatVersion: 2010-09-09
Description: |
  This Tamplate create Phonebook App with Database MYSql 
  
Parameters:
  InstanceType:
    Description: Select Your Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
      - t3.micro
      - m1.small
  
  MyKeyName:
    Description: Sellect Your KeyName
    Type: AWS::EC2::KeyPair::KeyName

  SubnetId:
    Description: Select All the Subnet
    Type: List<AWS::EC2::Subnet::Id>
  
  MyVPC:
    Description: Chouse Your VPC
    Type: AWS::EC2::VPC::Id


Mappings:
  RagionImageMap:
    us-east-1:
      AMI: ami-0b5eea76982371e91
    us-east-2:
      AMI: ami-0233c2d874b811deb
    us-west-1:
      AMI: ami-0ed05376b59b90e46
    us-west-2:
      AMI: ami-0dc8f589abe99f538
    eu-west-1:
      AMI: ami-058b1b7fe545997ae

Resources:
  EC2PhonebookSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "EC2 SSH and HTTP port 22 and 80 request"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref MyVPC

  rRDSSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable MySQL connection on port 3306
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !GetAtt EC2PhonebookSecGrp.GroupId
      VpcId: !Ref MyVPC

  PhoneboookDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 25
      BackupRetentionPeriod: 10
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: EminPhonebook
      DBName: EminBook
      Engine: mysql
      EngineVersion:  8.0
      PubliclyAccessible: true
      StorageType: gp2
      MasterUserPassword: emin1234
      MasterUsername: Admin
      MaxAllocatedStorage: 30 
      VPCSecurityGroups:
      - !GetAtt rRDSSecGroup.GroupId

  EC2LanchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !FindInMap 
          - RagionImageMap
          - !Ref AWS::Region
          - AMI
        InstanceType: !Ref InstanceType
        KeyName: !Ref MyKeyName
        SecurityGroupIds:
          - !GetAtt EC2PhonebookSecGrp.GroupId
        UserData: 
          Fn::Base64:
            !Sub 
              - |
                #! /bin/bash
                yum update -y
                yum install python3 -y
                pip3 install flask
                pip3 install flask_mysql
                echo "${MyDBURI}" > /home/ec2-user/dbserver.endpoint
                TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
                FOLDER="https://$TOKEN@raw.githubusercontent.com/bostantrt1/private-my-project/main/Project-004-Phonebook-Application"
                curl -s --create-dirs -o "/home/ec2-user/templates/index.html" -L "$FOLDER"/templates/index.html
                curl -s --create-dirs -o "/home/ec2-user/templates/add-update.html" -L "$FOLDER"/templates/add-update.html
                curl -s --create-dirs -o "/home/ec2-user/templates/delete.html" -L "$FOLDER"/templates/delete.html
                curl -s --create-dirs -o "/home/ec2-user/phonebook-app.py" -L "$FOLDER"/phonebook-app.py
                python3 /home/ec2-user/phonebook-app.py
              - MyDBURI: !GetAtt MyDatabaseServer.Endpoint.Address
      LaunchTemplateName: PhonebookLhanceTemplate
      
  PhonebookLoadeBalancing:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: PhonebookAplicationLB
      SecurityGroups:
        - !GetAtt EC2PhonebookSecGrp.GroupId
      Subnets: !Ref SubnetId
      Type: application

  PhoneBookTargetGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      VpcId: !Ref MyVPC

  PhonebookListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: # Required
        - Type: forward
          TargetGroupArn: !Ref PhoneBookTargetGrp
      LoadBalancerArn: !Ref PhonebookLoadeBalancing
      Port: 80
      Protocol: HTTP

  PhonebookAoutoScalingGrp:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 2
      HealthCheckGracePeriod: 90
      HealthCheckType: ELB
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LanchTemplate
        Version: 1
      MaxSize: 3
      MinSize: 1
      VPCZoneIdentifier: !Ref SubnetId
      TargetGroupARNs:
        - !Ref PhoneBookTargetGrp
      

  PhonebookAutoScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref PhonebookAoutoScalingGrp
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 60.0

Outputs: 
  ShowDNS:
    Description: Information DNS ALB
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt PhonebookLoadeBalancing.DNSName