AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - m4.large
  MyKeyPair:
    Description: Select Your KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  
Resources:
  WebServerHost:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair
      ImageId: ami-0b5eea76982371e91
      SecurityGroups:
        - !Ref WebSerwerSecurityGroup
      UserData:
        'Fn::Base64':
          !Sub |
            yum update -y
            yum install python3 -y
            pip3 install flask
            yum install git -y
            cd /home/ec2-user
            wget -P templates https://raw.githubusercontent.com/serdarcw/cli_deneme/master/templates/index.html
            wget -P templates https://raw.githubusercontent.com/serdarcw/cli_deneme/master/templates/result.html
            wget https://raw.githubusercontent.com/serdarcw/cli_deneme/master/app.py
            python3 app.py

         
  WebSerwerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Flask Web Server and SSH port to secure reach to my EC2
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of the EC2 instance
    Value: !Ref EC2Instance
  PublicDNS:
    Description: Public DNS of the EC2 instance
    Value: !GetAtt
            - EC2Instance
            - PublicDnsName
  PublicIP:
    Description: Public IP Adress of the EC2 instance
    Value: !GetAtt
            - EC2Instance
            - PublicIp