AWSTemplateFormatVersion: 2010-09-09
Description: |
  This Tamplate create Phonebook App with Database MYSql 
  

Resources:
  EC2PhonebookSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "EC2 SSH and HTTP port 22 and 80 request"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 

  rRDSSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable MySQL connection on port 3306
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !GetAtt EC2PhonebookSecGrp.GroupId
#    VpcId: !Ref pVpcID


  PhoneboookDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 25
      BackupRetentionPeriod: 10
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: EminPhonebook
      DBName: EminBook
      Engine: mysql
      EngineVersion:  8.0
      PubliclyAccessible: true
      StorageType: gp2
      MasterUserPassword: emin1234
      MasterUsername: Admin
      MaxAllocatedStorage: 30 
      VPCSecurityGroups:
      - !GetAtt rRDSSecGroup.GroupId


